DROP DATABASE IF EXISTS BooksLibrary;
CREATE DATABASE BooksLibrary;
USE BooksLibrary;

CREATE TABLE Book (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  image TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE Seller (
  id INT NOT NULL AUTO_INCREMENT,
  dpi VARCHAR(100) NOT NULL,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  address VARCHAR(100) NOT NULL,
  phone VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Sale (
  id INT NOT NULL AUTO_INCREMENT,
  sellerID INT NOT NULL,
  saleDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
  bookID INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (sellerID) REFERENCES Seller(id),
  FOREIGN KEY (bookID) REFERENCES Book(id)
);